
if(APPLE AND CMAKE_HOST_APPLE)
    MESSAGE(STATUS "OSX_ARCHITECTURES=${OSX_ARCHITECTURES}")
    set(Qt5_DIR "/opt/homebrew/opt/qt@5/lib/cmake/Qt5")
    set(OPENSSL_ROOT_DIR "/opt/homebrew/opt/openssl@3")
endif()

find_package(CapnProto REQUIRED)
find_package(Cython REQUIRED)
find_package(Threads REQUIRED)

find_package(PkgConfig REQUIRED)
pkg_check_modules(JPEG REQUIRED libjpeg)
pkg_check_modules(ZMQ REQUIRED libzmq)
pkg_check_modules(FFMPEG REQUIRED libavformat libavcodec libswscale libavutil)
pkg_check_modules(USB REQUIRED libusb-1.0)
pkg_check_modules(Z REQUIRED zlib)
find_package(OpenSSL COMPONENTS Crypto SSL REQUIRED)
pkg_check_modules(SYSTEMD libsystemd)
find_package(OpenCL REQUIRED)
if(OpenCL_FOUND)
    add_compile_definitions(CL_TARGET_OPENCL_VERSION=220)
endif()
pkg_check_modules(CURL REQUIRED libcurl)
