
option(BUILD_TESTING "build test files" OFF)
option(BUILD_EXTRAS "build misc extras, like setup and installer files" OFF)
option(BUILD_KAITAI "Regenerate kaitai struct parsers" OFF)
option(BUILD_ASAN "turn on ASAN" OFF)
option(BUILD_UBSAN "turn on UBSan" OFF)
option(BUILD_CLAZY "build with clazy" OFF)
option(BUILD_COMPILE_DB "build clang compilation database" OFF)
option(BUILD_SNPE "use SNPE on PC" OFF)
option(BUILD_NO_THNEED "avoid using thneed" ON)

option(BUILD_PANDA_FIRMWARE "Build Panda Firmware" ON)

option(BUILD_LTO "Build with LTO" ON)
if (BUILD_LTO)
    cmake_policy(SET CMP0069 NEW)
    include(CheckIPOSupported)
    check_ipo_supported(RESULT IPO_SUPPORT OUTPUT ipo_support_output)
endif()

set(TICI OFF)
if(EXISTS "/TICI")
    set(TICI ON)
    MESSAGE(STATUS "TICI=${TICI}")
endif()

set(USE_WEBCAM OFF)
if(DEFINED ENV{USE_WEBCAM})
    set(USE_WEBCAM ON)
    MESSAGE(STATUS "USE_WEBCAM=${USE_WEBCAM}")
endif()

if(BUILD_TESTING)
    find_package(Catch2 REQUIRED)
    include(CTest)
    include(Catch)
    include_directories(${CMAKE_SOURCE_DIR}/third_party/catch2/include)
endif()
