set(REDNOSE_CONFIG_TARGET)
set(REDNOSE_CONFIG_SCRIPT)
set(REDNOSE_CONFIG_ARG1)
set(REDNOSE_CONFIG_ARG2)
macro(RednoseConfig)
#    MESSAGE(STATUS "${ARGV0} ${ARGV1} [${ARGV2} ${ARGV3}]")
    list(APPEND REDNOSE_CONFIG_TARGET ${ARGV0})
    list(APPEND REDNOSE_CONFIG_SCRIPT ${ARGV1})
    list(APPEND REDNOSE_CONFIG_ARG1 ${ARGV2})
    list(APPEND REDNOSE_CONFIG_ARG2 ${ARGV3})
endmacro()

RednoseConfig("live" "${CMAKE_SOURCE_DIR}/selfdrive/locationd/models/live_kf.py" "1" "live_kf_constants.h")
RednoseConfig("car" "${CMAKE_SOURCE_DIR}/selfdrive/locationd/models/car_kf.py" "1" "")
if (NOT QCOM_BUILD)
    RednoseConfig("gnss" "${CMAKE_SOURCE_DIR}/selfdrive/locationd/models/gnss_kf.py" "1" "")
    RednoseConfig("loc_4" "${CMAKE_SOURCE_DIR}/selfdrive/locationd/models/loc_kf.py" "1" "")
    RednoseConfig("pos_computer_4" "${CMAKE_SOURCE_DIR}/rednose/helpers/lst_sq_computer.py" "0" "")
    RednoseConfig("pos_computer_5" "${CMAKE_SOURCE_DIR}/rednose/helpers/lst_sq_computer.py" "0" "")
    RednoseConfig("feature_handler_5" "${CMAKE_SOURCE_DIR}/rednose/helpers/feature_handler.py" "0" "")
    RednoseConfig("lane" "${CMAKE_SOURCE_DIR}/xx/pipeline/lib/ekf/lane_kf.py" "1" "")
endif()
